import React from "react";
const API="https://nexus-api-953z.onrender.com";
const H={"x-nexus-key":"nexus-axl-agent-key"};
export function AttributionTab(){
  const[d,setD]=React.useState(null);const[l,setL]=React.useState(true);
  React.useEffect(()=>{fetch(API+"/api/attribution/library",{headers:H}).then(r=>r.json()).then(d=>{setD(d);setL(false);}).catch(()=>setL(false));},[]);
  if(l)return <div style={{padding:"2rem",color:"#00ff88"}}>Loading Attribution...</div>;
  const s=d?.signals||d?.library||[];
  return <div style={{padding:"1.5rem",color:"#e0e0e0"}}><h2 style={{color:"#00ff88",marginBottom:"1rem"}}>Signal Attribution</h2>{s.length===0?<div style={{color:"#555",padding:"2rem",textAlign:"center"}}>Populates after 10 trades</div>:<div style={{display:"grid",gap:"8px"}}>{s.slice(0,15).map((x,i)=><div key={i} style={{background:"rgba(0,255,136,0.05)",border:"1px solid rgba(0,255,136,0.15)",borderRadius:"8px",padding:"10px 14px",display:"flex",justifyContent:"space-between"}}><span style={{color:"#fff"}}>{x.signal||x.name}</span><span style={{color:x.accuracy>60?"#00ff88":"#ffaa00"}}>{x.accuracy||0}%</span></div>)}</div>}</div>;
}
export function PoliticalIntelTab(){
  const[d,setD]=React.useState(null);const[l,setL]=React.useState(true);
  React.useEffect(()=>{fetch(API+"/api/whales",{headers:H}).then(r=>r.json()).then(d=>{setD(d);setL(false);}).catch(()=>setL(false));},[]);
  if(l)return <div style={{padding:"2rem",color:"#00ff88"}}>Loading Power Map...</div>;
  return <div style={{padding:"1.5rem",color:"#e0e0e0"}}><h2 style={{color:"#00ff88",marginBottom:"1rem"}}>Institutional Power Map</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(280px,1fr))",gap:"8px"}}>{(d?.filings||[]).map((f,i)=><div key={i} style={{background:"rgba(255,170,0,0.05)",border:"1px solid rgba(255,170,0,0.2)",borderRadius:"8px",padding:"12px"}}><div style={{color:"#ffaa00",fontWeight:"bold"}}>{f.entity}</div><div style={{color:"#888",fontSize:"12px"}}>Filed: {f.filed} | Period: {f.period}</div></div>)}</div></div>;
}
export function CryptoTab(){
  const[p,setP]=React.useState({});const[l,setL]=React.useState(true);
  const tix=["BTC-USD","ETH-USD","SOL-USD","BNB-USD","XRP-USD","DOGE-USD"];
  React.useEffect(()=>{Promise.all(tix.map(t=>fetch(API+"/api/yahoo-quote/"+t,{headers:H}).then(r=>r.json()).catch(()=>null))).then(res=>{const m={};tix.forEach((t,i)=>{if(res[i])m[t]=res[i];});setP(m);setL(false);});},[]);
  if(l)return <div style={{padding:"2rem",color:"#ffaa00"}}>Loading Crypto...</div>;
  return <div style={{padding:"1.5rem"}}><h2 style={{color:"#ffaa00",marginBottom:"1rem"}}>Crypto Intelligence</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(180px,1fr))",gap:"12px"}}>{tix.map(t=>{const d=p[t]||{};const price=d.price||0;const chg=d.change||0;return <div key={t} style={{background:"rgba(255,170,0,0.05)",border:"1px solid rgba(255,170,0,0.2)",borderRadius:"8px",padding:"1rem"}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:"8px"}}><span style={{color:"#ffaa00",fontWeight:"bold"}}>{t.replace("-USD","")}</span><span style={{color:chg>=0?"#00ff88":"#ff4444"}}>{chg>=0?"+":""}{typeof chg==="number"?chg.toFixed(2):chg}%</span></div><div style={{fontSize:"18px",fontWeight:"bold",color:"#fff"}}>${typeof price==="number"?price.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}):"N/A"}</div></div>})}</div></div>;
}
export function ConfidenceTab(){
  const[s,setS]=React.useState([]);const[l,setL]=React.useState(true);
  const tix=["NVDA","AAPL","PLTR","TSLA","AMD","META","MSFT","COIN"];
  React.useEffect(()=>{Promise.all(tix.map(t=>fetch(API+"/api/fundamental-score/"+t).then(r=>r.json()).catch(()=>null))).then(res=>{setS(res);setL(false);});},[]);
  if(l)return <div style={{padding:"2rem",color:"#00ff88"}}>Calculating Confidence Scores...</div>;
  return <div style={{padding:"1.5rem"}}><h2 style={{color:"#00ff88",marginBottom:"1rem"}}>Confidence Scoring</h2><div style={{display:"grid",gap:"8px"}}>{tix.map((t,i)=>{const d=s[i]||{};const score=d.score||50;const grade=d.grade||"C";const color=score>=65?"#00ff88":score>=50?"#ffaa00":"#ff4444";return <div key={t} style={{background:"rgba(0,0,0,0.3)",border:"1px solid rgba(255,255,255,0.08)",borderRadius:"8px",padding:"12px",display:"grid",gridTemplateColumns:"80px 1fr 80px 40px",alignItems:"center",gap:"12px"}}><span style={{color:"#fff",fontWeight:"bold"}}>{t}</span><div style={{height:"6px",background:"rgba(255,255,255,0.1)",borderRadius:"3px",overflow:"hidden"}}><div style={{width:score+"%",height:"100%",background:color,borderRadius:"3px"}}/></div><span style={{color,textAlign:"right"}}>{score}/100</span><span style={{color,fontWeight:"bold",textAlign:"center"}}>{grade}</span></div>})}</div></div>;
}
export function LeaderboardTab(){
  const[d,setD]=React.useState(null);const[l,setL]=React.useState(true);
  React.useEffect(()=>{fetch(API+"/api/leaderboard",{headers:H}).then(r=>r.json()).then(d=>{setD(d);setL(false);}).catch(()=>setL(false));},[]);
  if(l)return <div style={{padding:"2rem",color:"#00ff88"}}>Loading Leaderboard...</div>;
  const trades=d?.leaderboard||d?.trades||d?.picks||[];
  return <div style={{padding:"1.5rem"}}><h2 style={{color:"#00ff88",marginBottom:"0.5rem"}}>Top Performing Picks</h2><div style={{color:"#555",fontSize:"12px",marginBottom:"1rem"}}>Ranked by return</div>{trades.length===0?<div style={{color:"#555",textAlign:"center",padding:"3rem"}}>No completed trades yet</div>:<div style={{display:"grid",gap:"6px"}}>{trades.slice(0,20).map((t,i)=><div key={i} style={{background:"rgba(0,0,0,0.3)",border:"1px solid rgba(255,255,255,0.08)",borderRadius:"8px",padding:"10px 14px",display:"grid",gridTemplateColumns:"30px 70px 80px 1fr 80px",gap:"8px",fontSize:"13px",alignItems:"center"}}><span style={{color:"#555"}}>#{i+1}</span><span style={{color:"#fff",fontWeight:"bold"}}>{t.ticker}</span><span style={{color:t.direction==="CALL"?"#00ff88":"#ff4444"}}>{t.direction}</span><span style={{color:"#888",overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{t.catalyst||""}</span><span style={{color:t.outcome==="WIN"?"#00ff88":t.outcome==="LOSS"?"#ff4444":"#888",textAlign:"right"}}>{t.outcome||"open"}</span></div>)}</div>}</div>;
}
export function GreeksTab(){
  const[d,setD]=React.useState(null);const[tk,setTk]=React.useState("NVDA");const[l,setL]=React.useState(false);
  React.useEffect(()=>{setL(true);fetch(API+"/api/yahoo-chain/"+tk,{headers:H}).then(r=>r.json()).then(d=>{setD(d);setL(false);}).catch(()=>setL(false));},[tk]);
  const calls=d?.calls||[];const puts=d?.puts||[];
  return <div style={{padding:"1.5rem"}}><div style={{display:"flex",alignItems:"center",gap:"1rem",marginBottom:"1.5rem"}}><h2 style={{color:"#00ff88"}}>Options Greeks</h2><select value={tk} onChange={e=>setTk(e.target.value)} style={{background:"rgba(0,0,0,0.5)",border:"1px solid rgba(0,255,136,0.3)",color:"#fff",padding:"4px 8px",borderRadius:"4px"}}>{["NVDA","AAPL","TSLA","AMD","PLTR","META","MSFT","SPY","QQQ"].map(t=><option key={t} value={t}>{t}</option>)}</select>{l&&<span style={{color:"#888",fontSize:"12px"}}>Loading...</span>}</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"1rem"}}><div><div style={{color:"#00ff88",fontWeight:"bold",marginBottom:"8px"}}>CALLS</div>{calls.length===0?<div style={{color:"#555",padding:"1rem"}}>No calls data</div>:calls.slice(0,8).map((c,i)=><div key={i} style={{background:"rgba(0,255,136,0.05)",border:"1px solid rgba(0,255,136,0.15)",borderRadius:"6px",padding:"8px",fontSize:"12px",marginBottom:"4px",display:"grid",gridTemplateColumns:"60px 60px 50px 50px",gap:"8px"}}><span style={{color:"#fff"}}>K:{c.strike}</span><span style={{color:"#888"}}>{c.delta!=null?"d:"+c.delta.toFixed(2):""}</span><span style={{color:"#888"}}>{c.impliedVolatility!=null?"IV:"+(c.impliedVolatility*100).toFixed(0)+"%":""}</span><span style={{color:"#ffaa00"}}>${c.lastPrice?.toFixed(2)||"?"}</span></div>)}</div><div><div style={{color:"#ff4444",fontWeight:"bold",marginBottom:"8px"}}>PUTS</div>{puts.length===0?<div style={{color:"#555",padding:"1rem"}}>No puts data</div>:puts.slice(0,8).map((p,i)=><div key={i} style={{background:"rgba(255,68,68,0.05)",border:"1px solid rgba(255,68,68,0.15)",borderRadius:"6px",padding:"8px",fontSize:"12px",marginBottom:"4px",display:"grid",gridTemplateColumns:"60px 60px 50px 50px",gap:"8px"}}><span style={{color:"#fff"}}>K:{p.strike}</span><span style={{color:"#888"}}>{p.delta!=null?"d:"+p.delta.toFixed(2):""}</span><span style={{color:"#888"}}>{p.impliedVolatility!=null?"IV:"+(p.impliedVolatility*100).toFixed(0)+"%":""}</span><span style={{color:"#ffaa00"}}>${p.lastPrice?.toFixed(2)||"?"}</span></div>)}</div></div></div>;
}
export function DocsTab(){
  const eps=[["GET","/api/intelligence","key","Top 5 AI picks"],["GET","/api/signals","","All 20 signals"],["GET","/api/news","","66 articles from 14 sources"],["GET","/api/whales","","13F — Berkshire Bridgewater Scion"],["GET","/api/ticker-universe","","700+ tickers"],["GET","/api/fundamental-score/:ticker","","P/E margins growth 1-100"],["GET","/api/mtf/:ticker","","RSI MACD SR 1D and 1H"],["GET","/api/yahoo-quote/:ticker","","Live price volume"],["GET","/api/yahoo-chain/:ticker","","Options chain with greeks"],["GET","/api/leaderboard","","Top picks by return"],["GET","/api/tracker","","All trades with outcomes"],["GET","/api/oracle-brain","","Brain weights evolution"],["GET","/api/p2-intelligence","","Dark pool Form4 congress"],["POST","/api/fundamental-scores","","Batch scores 10 tickers"]];
  return <div style={{padding:"1.5rem",color:"#e0e0e0"}}><h2 style={{color:"#00ff88",marginBottom:"0.5rem"}}>NEXUS API Reference</h2><div style={{color:"#555",fontSize:"12px",marginBottom:"1.5rem"}}>Base: https://nexus-api-953z.onrender.com</div><div style={{display:"grid",gap:"6px"}}>{eps.map((e,i)=><div key={i} style={{background:"rgba(0,0,0,0.3)",border:"1px solid rgba(255,255,255,0.08)",borderRadius:"8px",padding:"10px 14px",display:"grid",gridTemplateColumns:"50px 240px 40px 1fr",alignItems:"center",gap:"12px",fontSize:"12px"}}><span style={{color:e[0]==="GET"?"#0088ff":"#ffaa00",fontWeight:"bold"}}>{e[0]}</span><span style={{color:"#00ff88",fontFamily:"monospace"}}>{e[1]}</span><span style={{color:e[2]?"#ffaa00":"transparent",fontSize:"11px"}}>{e[2]?"KEY":""}</span><span style={{color:"#888"}}>{e[3]}</span></div>)}</div><div style={{marginTop:"1.5rem",padding:"1rem",background:"rgba(0,255,136,0.05)",border:"1px solid rgba(0,255,136,0.2)",borderRadius:"8px"}}><div style={{color:"#00ff88",fontWeight:"bold",marginBottom:"8px"}}>Auth</div><div style={{fontSize:"12px",color:"#888"}}>Header: x-nexus-key: nexus-axl-agent-key</div></div></div>;
}
